"""Utility functions and helpers."""

from .prompts import (
    SUPERVISOR_AGENT_SYSTEM_PROMPT,
    PAPER_AGENT_SYSTEM_PROMPT,
    SLIDES_AGENT_SYSTEM_PROMPT,
    QUIZ_GENERATOR_SYSTEM_PROMPT,
    FLASHCARD_GENERATOR_SYSTEM_PROMPT,
    METADATA_CURRENT_TEACHING_CHECK,
    METADATA_ENRICHMENT_PROMPT,
    format_conversation_history,
    format_context
)

__all__ = [
    'SUPERVISOR_AGENT_SYSTEM_PROMPT',
    'PAPER_AGENT_SYSTEM_PROMPT',
    'SLIDES_AGENT_SYSTEM_PROMPT',
    'QUIZ_GENERATOR_SYSTEM_PROMPT',
    'FLASHCARD_GENERATOR_SYSTEM_PROMPT',
    'METADATA_CURRENT_TEACHING_CHECK',
    'METADATA_ENRICHMENT_PROMPT',
    'format_conversation_history',
    'format_context'
]
